# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80a5e711f7cc6d770b7ceb7038db920a"
name = "theonlyappever"
handle = "theonlyappever"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
